export const CLIENT_SIGNUP = 'CLIENT_SIGNUP';
export const CLIENT_SIGNUP_SUCCESS = 'CLIENT_SIGNUP_SUCCESS';
export const CLIENT_SIGNUP_FALIURE = 'CLIENT_SIGNUP_FALIURE';
export const GET_CLIENT_DATA = 'GET_CLIENT_DATA';
export const GET_CLIENT_DATA_SUCCESS = 'GET_CLIENT_DATA_SUCCESS';
export const GET_CLIENT_DATA_FAILURE = 'GET_CLIENT_DATA_FAILURE';