export const FETCH_CASE_DETAIL = 'FETCH_CASE_DETAIL';
export const FETCH_CASE_DETAIL_SUCCESS = 'FETCH_CASE_DETAIL_SUCCESS';
export const FETCH_CASE_DETAIL_FALIURE = 'FETCH_CASE_DETAIL_FALIURE';
export const UPDATE_CASE_DETAIL = 'UPDATE_CASE_DETAIL';
export const UPDATE_CASE_DETAIL_SUCCESS = 'UPDATE_CASE_DETAIL_SUCCESS';
export const UPDATE_CASE_DETAIL_FAILURE = 'UPDATE_CASE_DETAIL_FAILURE';
export const CHANGE_CASE_STATUS = 'CHANGE_CASE_STATUS';